data_path: /working2/arctic/Recon/stanford_convert/
default_root_dir: ./experiments/standford2d_pdac_dymodel/
resume_from: null

batch_size: 1

# center-square mask size applied after each cascade
# num_list: [160, 224, 268, 302, 328, 350, 368, 384]
# num_list: [54, 140, 240, 306, 352, 370, 380, 384]
num_list: [48,96,144,192,240,288,336,384]

# dataset setting
accelerations:
- 8
center_fractions:
- 0.04
challenge: multicoil
check_val_every_n_epoch: 1
mask_type: random

# training setting
lr: 0.0001
lr_gamma: 0.1
lr_step_size: 45
weight_decay: 0.0
max_epochs: 50

# model setting
num_cascades: 8
train_val_seed: 0
seed: 42
sens_chans: 16
uniform_train_resolution:
- 384
- 384
train_val_split: 0.8
volume_sample_rate: 1.0
weight_decay: 0.0
embed_dim: 66
patch_size: 1
window_size: 8
depths: 
- 2
- 2
- 2
num_heads:
- 3
- 6
- 12
mlp_ratio: 2.0
resi_connection: 1conv
bottleneck_depth: 2
bottleneck_heads: 24
conv_downsample_first: True
num_adj_slices: 1
verbose: True
use_checkpointing: False
use_compile: True
use_bf16: True
